### ISSUE TITLE
Errore del riavvio

### ISSUE THREAD

**Issue by ghost** [peppelg/TGUserbot#1]
<pre>Riavvio... 
start.php: 2: start.php: cannot open ?php: No such file
start.php: 3: start.php: Syntax error: word unexpected (expecting ")")</pre>

**Comment by peppelg** [comment]
@TRIGGEREDNICK wtf

**Comment by TRIGGEREDNICK** [comment]
@peppelg Mi da questo errore....

**Comment by ghost** [comment]
Fixato!
