### ISSUE TITLE
Controllare più utenti

### ISSUE THREAD

**Issue by thedevale** [peppelg/TGUserbot#10]
Vorrei sapere se c'è un modo per far ricevere un determinato update, mandato ad un solo utente, a tutti gli utenti aggiunti alla base

**Comment by gachs** [comment]
Cioé, far ricevere solo un determinato update?

**Comment by gachs** [comment]
@gachs test

**Comment by thedevale** [comment]
Intendo, non ho intenzione di fare bot per flood o altro, ma prendiamo in considerazione l'esempio:

Io in qualche modo comunico a tutti gli userbots di entrare in un cane, in modo che da quel momento visualizzino tutti i post del canale.
Sparo, non è la mia idea

**Comment by thedevale** [comment]
*canale, pardon

**Comment by gachs** [comment]
Cioé vuoi inviare 1 solo update a tutti gli utenti nel db? :neutral_face: non capisk

**Comment by thedevale** [comment]
Premessa: non ho ancora mai sfruttato l'opzione "addaccount" di TGUserbot, quindi non ho mai usato account multipli sullo stesso script.
Ma vorrei provare a farlo. 
In poche parole: aggiungo un utente, faccio ciò che bisogna fare, e da quel momento lui sarà "in ascolto", e quando invierò un determinato comando (aggiungendo un record al database, o scrivendolo su file di testo, o mandandolo ad uno solo dei bot) tutti gli utenti lo riceveranno

**Comment by TheDeadKiller10** [comment]
@alexandrussmc Basta creare un gruppo e aggiungere tutti i tuoi userbot, tutti i userbot usano lo stesso file bot.php quindi sono praticamente uguali

**Comment by davtur19** [comment]
Lo puoi fare in molti modi, io per esempio ho sia un un gruppo e ultimamente sto facendo un bot normale per gestirli.
Basta fare in modo tale che all'avvio gli userbot avviino il bot, poi che il bot sia autorizzato ad eseguire comandi sugli userbot e infince gli userbot dovranno stampare un output in chat con il bot, quest'ultimo poi restituirà il risultato a te.
Così facendo quando darai un comando al bot, poi verrà inoltrato a tutti gli userbot (basta salvarti un array con tutti gli id degli utenti)
