### ISSUE TITLE
Start.php error

### ISSUE THREAD

**Issue by ghost** [peppelg/TGUserbot#13]
Error: Function name must be a string in phar:///root/me/TGUserbot/TGUserbot.phar/start.php:505
Stack trace:
#0 phar:///root/me/TGUserbot/TGUserbot.phar/start.php(455): TGUserbot->error(Object(Error))
#1 phar:///root/me/TGUserbot/TGUserbot.phar/start.php(352): TGUserbot->handleUpdate(Array)
#2 phar:///root/me/TGUserbot/TGUserbot.phar/start.php(170): TGUserbot->start()
#3 phar:///root/me/TGUserbot/TGUserbot.phar/start.php(620): TGUserbot->__construct()
#4 phar:///root/me/TGUserbot/TGUserbot.phar/tguserbot.php(65): require('phar:///root/me...')
#5 /root/me/TGUserbot/TGUserbot.phar(10): include('phar:///root/me...')
#6 {main}

**Comment by MattiaBLX** [comment]
@MattiaBLX oh ci sono io

**Comment by peppelg** [comment]
oK forse ho capit,,grazie domani vedo 💋

**Comment by BranchScope** [comment]
@MattiaBLX ah

**Comment by ghost** [comment]
@MattiaBLX Fixed.

**Comment by peppelg** [comment]
fixato 1OO%

**Comment by BranchScope** [comment]
@peppelg brv
