### ISSUE TITLE
Prendere tutti gli id di tutti gli utenti in un canale

### ISSUE THREAD

**Issue by Invy55** [peppelg/TGUserbot#17]
Non capisco perchè
if (stripos($msg, '!: ') === 0) {
  global $update;
  global $MadelineProto;
$chan=explode(' ', $msg, 2)[1];
$channels_ChannelParticipants = $MadelineProto->channels->getParticipants(['channel' => $chan, 'filter' => 'ChannelParticipantsAdmins', 'offset' => 0, 'limit' => 1000, 'hash' => [0, 100]]);
//echo $channels_ChannelParticipants;
sm('402072799', $channels_ChannelParticipants);
}`
l'userbot mi risponde 

> Errore: Predicate (value under _) was not set!

ma nella console is vede un array con un sacco di informazioni sugli utenti.

`While serializing:      channels.getParticipants['filter']
CallHandler.php(74):    serialize_method("channels.getParticipants",{"channel":"-1001312970878","filter":"ChannelParticipantsAdmins","offset":0,"limit":1000,"hash":[0,100]})
APIFactory.php(142):    method_call("channels.getParticipants",{"channel":"-1001312970878","filter":"ChannelParticipantsAdmins","offset":0,"limit":1000,"hash":[0,100]},{"datacenter":1,"apifactory":true})
start.php(618):         __call("getParticipants",[{"channel":"-1001312970878","filter":"ChannelParticipantsAdmins","offset":0,"limit":1000,"hash":[0,100]}])
start.php(610):         MadelineCall("channels","getParticipants",[{"channel":"-1001312970878","filter":"ChannelParticipantsAdmins","offset":0,"limit":1000,"hash":[0,100]}])
bot.php(32):            __call("getParticipants",[{"channel":"-1001312970878","filter":"ChannelParticipantsAdmins","offset":0,"limit":1000,"hash":[0,100]}])
start.php(450):         include("\/var\/grief\/TGUserbot\/bot.php")
start.php(352):         handleUpdate[arrayprivato]
start.php(170):         start()
start.php(626):         __construct()
tguserbot.php(65):      require("phar:\/\/\/var\/grief\/TGUserbot\/TGUserbot.phar\/start.php")
TGUserbot.phar(10):     include("phar:\/\/\/var\/grief\/TGUserbot\/TGUserbot.phar\/tguserbot.php")
nome >>> Errore: Predicate (value under _) was not set!`

**Comment by Invy55** [comment]
@Invy55 raga qualcuno sa risuolvere

**Comment by peppelg** [comment]
IL problema non è di tguserobot ma del tuo codice ;;;passo e chiudo ;aguriamo buon giornata

**Comment by TyroneFromJail** [comment]
@Invy55 che fetoraggine
