### ISSUE TITLE
madeline.phar cannot be required manually: use the automatic loader.

### ISSUE THREAD

**Issue by yusufusta** [peppelg/TGUserbot#20]
@peppelg 
oot@orangepione:/home/yusuf/TGUserbot# ./TGUserbot.phar
Sto caricando MadelineProto...
Fatto!
madeline.phar cannot be required manually: use the automatic loader, instead: https://docs.madelineproto.xyz/docs/INSTALLATION.html#simple
root@orangepione:/home/yusuf/TGUserbot#

How to fix?

**Comment by ghost** [comment]
Just wait for peppelg merge my pull request https://github.com/peppelg/TGUserbot/pull/19

**Comment by yusufusta** [comment]
Fixed.
