### ISSUE TITLE
Nel Cli vengono scritti i messaggi che vengono inviati dall'userbot

### ISSUE THREAD

**Issue by neneone** [peppelg/TGUserbot#22]
Ho attivato la funzione Cli e quando scrivo per esempio `messages.sendMessage {"peer":"@Nen3one","message":"Ciao"}` viene scritto l'output e poi anche il messaggio come se l'userbot l'avesse ricevuto.

**Comment by peppelg** [comment]
@Neneone e wuale e u problema

**Comment by Neneone** [comment]
@peppelg

**Comment by neneone** [comment]
Non deve mostrare il messaggio come se l'avesse ricevuto da qualcuno...
![ ](https://user-images.githubusercontent.com/28790048/58028704-98d5e980-7b1b-11e9-968a-6728560f0da0.png)

**Comment by peppelg** [comment]
![aa](https://user-images.githubusercontent.com/29309124/58318570-4eed4c00-7e18-11e9-9a53-acdc059fda74.jpg)
È una cosa voluta,,tguserbot mostra anche mex del bot stesso
