### ISSUE TITLE
CronjobAdd

### ISSUE THREAD

**Issue by thedevale** [peppelg/TGUserbot#8]
La funzione è scomparsa :)

**Comment by peppelg** [comment]
Con la nuova versione è $cron->add().

**Comment by ghost** [comment]
bello bello

**Comment by Loryitaly** [comment]
anche se non capisco un cazz
`public void initString() {

	// capitolo 1:ho bisogno di aiuto
	String titolo = new String("AIUTO");
	
	// da voi
	char[] array = {aiuto!!'};
	
	String sottotitolo = new String(ho bisogno di aiutoì');
}`

**Comment by nicknessuno01** [comment]
@peppelg peppelg/TGUserbot

**Comment by gachs** [comment]
:smile:

**Comment by gachs** [comment]
@gachs
