### ISSUE TITLE
Grazie mille

### ISSUE THREAD

**Issue by gachs** [peppelg/TGUserbot#9]
Questa tecnologia non spamma bambini. PORQUE OO

**Comment by peppelg** [comment]
Pls smettetela di vandalizzare la repo


Grazie

**Comment by ghost** [comment]
la repo agga

**Comment by ghost** [comment]
riaprite l'issue

**Comment by gachs** [comment]
cos

**Comment by ghost** [comment]
@gachs Pedo

**Comment by ghost** [comment]
@gachs Peppelg1 scammer

**Comment by peppelg** [comment]
@TRIGGEREDNICK il prossimo che vandalizza la repo viene bloccato

**Comment by gachs** [comment]
assort @mattiablx

**Comment by ghost** [comment]
@mattiablx non credo sia il caso

**Comment by ghost** [comment]
Ma cosa, è un issue hihihi

**Comment by ghost** [comment]
@TRIGGEREDNICK Allora è la casa

**Comment by ghost** [comment]
pure closed

**Comment by gachs** [comment]
@TRIGGEREDNICK lol

**Comment by ghost** [comment]
agga

**Comment by ghost** [comment]
bo

**Comment by gachs** [comment]
@TRIGGEREDNICK be

**Comment by ghost** [comment]
@TRIGGEREDNICK Rocco cancro

**Comment by gachs** [comment]
CIAO MEMBRI DI TGUSERBOT.#

**Comment by ghost** [comment]
@gachs Coso zitto

**Comment by gachs** [comment]
@peppelg chiudi sta robba 

> Gay

**Comment by ghost** [comment]
@gachs ZITTOOOO

**Comment by peppelg** [comment]
![image](https://user-images.githubusercontent.com/29309124/38456107-d86d3c4c-3a80-11e8-9d57-17f2b01fcd66.png)
non obbligatemi

**Comment by gachs** [comment]
![fabrizio-frizzi-la-vera-malattia-che-lo-ha-ucciso-fabrizio-frizzi-morto](https://user-images.githubusercontent.com/32957407/38456115-ee95d8b2-3a80-11e8-91fe-263707cf151a.png)
frizzi .

**Comment by ghost** [comment]
ALlora
